project:
  type: website

website:
  site-url: https://hprtc.org.au
  title: "Heathmont Parker Reserve Tennis Club"
  favicon: img/favicon.ico
  google-analytics: "UA-156112561-1"
  navbar:
    background: "#dfdfdf"
    title: "&nbsp;"
    pinned: true
    search: true
    logo: img/hprtc_logo.png
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        menu:
          - about/conduct.qmd
          - about/committee.qmd
          - about/history.qmd
          - about/constitution.qmd
          - about/lifemembers.qmd
          - text: Legal
            href: about/legal.qmd
      - text: "Coaching"
        href: coaching.qmd
      - text: "Competition"
        menu:
          - competition/adult.md
          - competition/junior.md
      - text: "Social"
        href: social.md
      - news/index.qmd
      - facilities.qmd
      - text: "Members"
        href: members.md
      - text: "Contact"
        href: contact.md
  page-footer:
    left: "© 2023 Heathmont Parker Reserve Tennis Club"
    background: "#555555"
    right: Made with [Quarto](https://quarto.org) by [Rob J Hyndman](https://robjhyndman.com)

date-format: "D MMMM YYYY"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      file: header.html

execute:
  freeze: true
  echo: false
  message: false
